### ISSUE TITLE
Play Sound in background

### ISSUE THREAD

**Issue by xabree** [expo/video-background-example#1]
I'm trying to play mp3 file with Exponent.Components.Video, running well in exponent client. 
I have an issue when exp client is closed or phone in lockscreen mode, the sound is stopped. can I use play in background, can I use props <Exponent.Components.Video playInBackground={true} playWhenInactive={true}" like react-native-video? 

when running video in background, can I use native controll in Ios to stop or play video, like pic bellow?
<img width="372" alt="screen shot 2017-01-04 at 8 06 31 am" src="https://cloud.githubusercontent.com/assets/24905186/21628924/1bac3466-d256-11e6-98bd-d7c9d90ca0e8.png">

**Comment by terribleben** [comment]
Hi there!

First, I want to clarify that this repository is an example of how to use a Video as a visual background element in your app, not how to play video when the app is running in the background. Sorry for the ambiguous use of the word "background."

To answer your question, we don't support background audio yet because the API on iOS is a bit more restrictive (you need a way of telling iOS how to mix your app's sound with other apps).

Having a real sound API on exponent (instead of the Video component), including better support for background audio, is near on our roadmap. Exponent also sandboxes your app from other Exponent experiences, so the permissions model is slightly different. Those are the reasons why we didn't adopt the exact same background API as `react-native-video`.

Hopefully we'll be able to land better background audio support soon.
